# -*- coding: utf-8 -*-
"""第一章綜合範例.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EvmHs1aG8vv3GCN-tEBABt_OyyYzz6iY
"""

# 請使用者輸入攝氏溫度，然後輸出其對應的華氏溫度。

cDegree = eval(input())
fDegree = (9/5)*cDegree+32

print("Celsis %.2f ---> Fahrenheit %.2f"%(cDegree,fDegree))

# 請使用者輸入三角形的三點座標，然後計算此三角形的面積。
# 提示：假設三角形三個點的座標為(x1,y1),(x2,y2),(x3,y3)，則三邊的長分別為side1,side2,以及side3。
# 利用綜合範例8可得到這三邊的長。然後利用下列公式即可得到此三角形的面積。
# s＝(side1＋side2＋side3)/2
# area＝√s＊(s-side1)＊(s-side2)＊(s-side3)


import math
x1,y1=eval(input())
x2,y2=eval(input())
x3,y3=eval(input())

side1=math.sqrt((x2-x1)**2+(y2-y1)**2)
side2=math.sqrt((x3-x1)**2+(y3-y1)**2)
side3=math.sqrt((x3-x2)**2+(y3-y2)**2)

s=(side1+side2+side3)/2
area=math.sqrt((s*(s-side1)*(s-side2)*(s-side3)))
print("The area of the triangle=%.2f"%(area))

# 請使用者輸入矩形的長和寬(皆為正整數)，然後計算此矩形的面積和周長(輸出結果欄位為4)。

length,width=eval(input())
area=length*width
perimeter=2*(length+width)
print("area=%4d"%(area))
print("perimeter=%4d"%(perimeter))

# 請使用者輸入起始的速度v0、結束的速度v1，然後顯示其平均速度。

v0,v1,t = eval(input())
a=(v1-v0)/t
print("average acceleration is %.2f"%(a))

# 假設你每個月在帳戶存款10000，銀行的年利率為1.23%，也就是說，月利率為0.0123/12=0.001025。
# 一個月後，帳戶的存款會是：10000*(1+0.001025)=10010.25
# 兩個月過後，帳戶的存款會變成：10010.25*(1+0.001025)=10020.51
# 三個月過後，帳戶的存款會變成：10020.51*(1+0.001025)=10030.78，依此類推。
# 請撰寫一程式，提示使用者每個月存入帳戶的金額，並顯示六個月後帳戶裏的總金額(輸出到小數點後2位)。

monthlyDeposit=eval(input("Enter monthly saving amount: "))
currentValue=monthlyDeposit

# First month value
currentValue = currentValue * (1 + 0.0123 / 12)

# Second month value
currentValue = currentValue * (1 + 0.0123 / 12)

# Third month value
currentValue = currentValue * (1 + 0.0123 / 12)

# Fourth month value
currentValue = currentValue * (1 + 0.0123 / 12)

# Fifth month value
currentValue = currentValue * (1 + 0.0123 / 12)

# Sixth month value
currentValue = currentValue * (1 + 0.0123 / 12)

print("After the sixth month, the account value is %.2f",%(currentValue))